name: SPGPylibs_env
channels:
  - defaults
dependencies:
  - ca-certificates=2022.2.1=hecd8cb5_0
  - certifi=2021.10.8=py39hecd8cb5_2
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - ncurses=6.3=hca72f7f_2
  - openssl=1.1.1m=hca72f7f_0
  - pip=21.2.4=py39hecd8cb5_0
  - python=3.9.7=h88f2d9e_1
  - readline=8.1.2=hca72f7f_1
  - setuptools=58.0.4=py39hecd8cb5_0
  - sqlite=3.37.2=h707629a_0
  - tk=8.6.11=h7bc2e8c_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h4dc903c_4
  - pip:
    - astropy==4.2.1
    - cycler==0.11.0
    - cython==0.29.28
    - fonttools==4.29.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - numpy==1.22.2
    - packaging==21.3
    - photutils==1.3.0
    - pillow==9.0.1
    - pyerfa==2.0.0.1
    - pyfftw==0.13.0
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - six==1.16.0
    - spiceypy==3.0.2
    - threadpoolctl==3.1.0
    - tqdm==4.62.3
prefix: /Users/orozco/opt/miniconda3/envs/SPGPylibs_env
